name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: debian:bookworm-slim

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag porcupine-pipeline:$(date +%s)
